import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Firebase configuration options for BikeRide
///
/// Generated by FlutterFire CLI on 2026-03-11
/// Project: biko-f1bfa
///
/// Run: `flutterfire configure` to regenerate.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-3H3NpU_gHfMNseCMFcgJlQXB0L9eG0',
    appId: '1:283152900428:android:62a906efdab6b9e9942fe9',
    messagingSenderId: '283152900428',
    projectId: 'biko-f1bfa',
    databaseURL: 'https://biko-f1bfa-default-rtdb.firebaseio.com',
    storageBucket: 'biko-f1bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6lb1N14W2p5V0lF7ec-2Q1B23qX_H23o',
    appId: '1:283152900428:ios:15a809651dc16c60942fe9',
    messagingSenderId: '283152900428',
    projectId: 'biko-f1bfa',
    databaseURL: 'https://biko-f1bfa-default-rtdb.firebaseio.com',
    storageBucket: 'biko-f1bfa.firebasestorage.app',
    androidClientId: '283152900428-5flfpmm7ib95jo7g3q4aumuksjnkvij9.apps.googleusercontent.com',
    iosClientId: '283152900428-rkdt7fe7atl1r41s8mvifto6686pjahh.apps.googleusercontent.com',
    iosBundleId: 'com.example.biko',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb5QTG8DSmY0iSMSzb9hIsZDRo1y5mnvM',
    appId: '1:283152900428:web:9e0fc6a44bc01b13942fe9',
    messagingSenderId: '283152900428',
    projectId: 'biko-f1bfa',
    authDomain: 'biko-f1bfa.firebaseapp.com',
    databaseURL: 'https://biko-f1bfa-default-rtdb.firebaseio.com',
    storageBucket: 'biko-f1bfa.firebasestorage.app',
    measurementId: 'G-WXC7PE1K6N',
  );
}
