import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Firebase configuration options for BikeRide
///
/// Generated by FlutterFire CLI. Replace these placeholder values
/// with real Firebase project configuration.
///
/// Run: `flutterfire configure` to regenerate.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  // TODO: Replace with actual Firebase project configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:000000000000:android:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'bikeride-placeholder',
    storageBucket: 'bikeride-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:000000000000:ios:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'bikeride-placeholder',
    storageBucket: 'bikeride-placeholder.appspot.com',
    iosBundleId: 'com.bikeride.customer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:000000000000:web:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'bikeride-placeholder',
    storageBucket: 'bikeride-placeholder.appspot.com',
    authDomain: 'bikeride-placeholder.firebaseapp.com',
  );
}
